language:
  - php
  - c

compiler:
  - gcc
  - clang
  
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  
matrix:
  allow_failures:
    - php: 7.0
    
env:
  - CC="gcc"
  - CC="clang"

services:
  - memcached
  - redis-server

install:
  - composer --prefer-source install

before_script:
  - phpenv config-add tests/ci/drivers.ini
  - git submodule --quiet update --init --recursive
  - (cd vendor/phalcon/zephir; ./unit-tests/ci/before_install.sh; ./install)
  - ./vendor/bin/zephir generate
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; phpize && ./configure --enable-owl && make --silent -j4 && sudo make --silent install && phpenv config-add ../tests/ci/owl.ini)
  - ulimit -c unlimited || true

script:
  - (cd examples/rest-app; composer install; php public/index.php)
  - phpunit

after_failure:
  - sudo apt-get -qq install gdb
  - ./tests/ci/after_failure.sh
